import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

// Simple redirect handler for Cloudflare Pages
export function onRequest(context) {
  // Return a simple redirect to the client-side app
  return new Response(null, {
    status: 302,
    headers: {
      Location: '/',
    },
  });
}