import type { ServerBuild } from '@remix-run/node';
import { createRequestHandler } from '@remix-run/netlify';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

export const handler = createRequestHandler({
  build: serverBuild as unknown as ServerBuild,
  mode: process.env.NODE_ENV,
  getLoadContext(event) {
    return {
      env: process.env,
    };
  },
});
