[build]
  command = "pnpm run build"
  publish = "build/client"
  node_bundler = "esbuild"

[dev]
  command = "pnpm run dev"
  port = 5173
  targetPort = 5173

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--version"
  PNPM_VERSION = "9.4.0"