[build]
  command = "pnpm install && pnpm run build"
  publish = "public"
  node_bundler = "esbuild"

[dev]
  command = "pnpm run dev"
  port = 5173
  targetPort = 5173

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["build/server/**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/path-handler"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/path-handler"
  status = 200

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--version"
  PNPM_VERSION = "9.4.0"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https: wss:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; connect-src 'self' https: wss:; worker-src 'self' blob:; child-src 'self' blob:; frame-src 'self' https:;"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"